all: zad2a_1 zad2a_2 zad2a_3 zad2a_4 zad2a_5

zad2a_1: zad2a_1.c
	gcc -Wall zad2a_1.c -o zad2a_1.run -lpthread

zad2a_2: zad2a_2.c
	gcc -Wall zad2a_2.c -o zad2a_2.run -lpthread

zad2a_3: zad2a_3.c
	gcc -Wall zad2a_3.c -o zad2a_3.run -lpthread

zad2a_4: zad2a_4.c
	gcc -Wall zad2a_4.c -o zad2a_4.run -lpthread

zad2a_5: zad2a_5.c
	gcc -Wall zad2a_5.c -o zad2a_5.run -lpthread

zad2b: zad2b.c
	gcc -Wall zad2b.c -o zad2b.run -lpthread

clean:
	rm -f zad2a_1.run zad2a_2.run zad2a_3.run zad2a_4.run zad2a_5.run zad2b.run